"""Curated official browsing entries; these are not automated catalog adapters.

Only an explicit human click opens a source website. The local search service
never fetches these URLs. Official entries were checked on 2026-10-08; resource
pricing, download access and licenses must be checked on each source page.
"""

EXTERNAL_PROVIDERS = [{'id': 'itchio',
  'name': 'itch.io',
  'kinds': ['model', 'texture', 'vfx', 'other'],
  'mode': 'external',
  'defaultKind': 'other',
  'core': True,
  'group': 'catalog',
  'searchUrlTemplate': 'https://itch.io/search?q={query}&facets=c.2',
  'note': '独立游戏素材；免费与付费都有，许可按作者说明核对。'},
 {'id': 'unity',
  'name': 'Unity Asset Store',
  'kinds': ['model', 'texture', 'vfx', 'other'],
  'mode': 'external',
  'defaultKind': 'vfx',
  'core': True,
  'group': 'catalog',
  'searchUrlTemplate': 'https://marketplace.unity.com/search?q={query}',
  'note': 'Unity 模型、特效和素材包；先看价格、许可与渲染管线。'},
 {'id': 'fab',
  'name': 'Fab',
  'kinds': ['model', 'texture', 'hdri', 'vfx', 'other'],
  'mode': 'external',
  'defaultKind': 'model',
  'core': True,
  'group': 'catalog',
  'searchUrlTemplate': 'https://www.fab.com/search?q={query}',
  'note': '模型、材质与游戏素材市场；各项价格和许可分别核对。'},
 {'id': 'cgtrader',
  'name': 'CGTrader',
  'kinds': ['model'],
  'mode': 'external',
  'defaultKind': 'model',
  'core': False,
  'group': 'catalog',
  'searchUrlTemplate': 'https://www.cgtrader.com/search?keywords={query}',
  'note': '模型市场；免费与付费都有，注意文件格式与许可。'},
 {'id': 'quaternius',
  'name': 'Quaternius',
  'kinds': ['model', 'other'],
  'mode': 'external',
  'defaultKind': 'model',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://quaternius.com/',
  'note': '风格化游戏模型与角色动画包；打开官网浏览，核对具体包的许可。'},
 {'id': 'kaykit',
  'name': 'KayKit',
  'kinds': ['model', 'other'],
  'mode': 'external',
  'defaultKind': 'model',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://kaylousberg.com/game-assets',
  'note': 'Kay Lousberg 的风格化游戏素材包；打开作者官网浏览。'},
 {'id': 'mixamo',
  'name': 'Mixamo',
  'kinds': ['model', 'other'],
  'mode': 'external',
  'defaultKind': 'model',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://www.mixamo.com/',
  'note': 'Adobe 角色、骨骼与动画资源；需要 Adobe ID，使用前核对条款。'},
 {'id': 'blenderkit',
  'name': 'BlenderKit / Blendkit',
  'kinds': ['model', 'texture', 'hdri', 'other'],
  'mode': 'external',
  'defaultKind': 'model',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://www.blendkit.com/',
  'note': 'Blender 模型、材质与场景；原 BlenderKit 官网现转到 Blendkit，免费与付费混合。'},
 {'id': 'blendswap',
  'name': 'Blend Swap',
  'kinds': ['model', 'other'],
  'mode': 'external',
  'defaultKind': 'model',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://blendswap.com/',
  'note': 'Blender 社区模型与场景；许可、账户和下载要求按项核对。'},
 {'id': 'free3d',
  'name': 'Free3D',
  'kinds': ['model'],
  'mode': 'external',
  'defaultKind': 'model',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://free3d.com/',
  'note': '免费与付费 3D 模型目录；先核对文件格式、用途限制和许可。'},
 {'id': 'turbosquid',
  'name': 'TurboSquid',
  'kinds': ['model'],
  'mode': 'external',
  'defaultKind': 'model',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://www.turbosquid.com/',
  'note': '大型免费与付费模型市场；打开网站浏览，逐项检查价格与许可。'},
 {'id': 'polypizza',
  'name': 'Poly Pizza',
  'kinds': ['model'],
  'mode': 'external',
  'defaultKind': 'model',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://poly.pizza/',
  'note': '适合游戏使用的低多边形模型；逐项核对作者与许可。'},
 {'id': 'smithsonian3d',
  'name': 'Smithsonian 3D',
  'kinds': ['model'],
  'mode': 'external',
  'defaultKind': 'model',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://3d.si.edu/',
  'note': '史密森学会馆藏扫描模型；内容适合参考与场景研究，按项核对开放使用条件。'},
 {'id': 'textures',
  'name': 'Textures.com',
  'kinds': ['texture', 'model', 'hdri', 'other'],
  'mode': 'external',
  'defaultKind': 'texture',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://www.textures.com/',
  'note': '纹理、PBR 素材与相关 3D 资源；额度、付费与许可按原页核对。'},
 {'id': 'cgbookcase',
  'name': 'CGBookcase',
  'kinds': ['texture'],
  'mode': 'external',
  'defaultKind': 'texture',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://www.cgbookcase.com/',
  'note': '免费 PBR 材质目录；打开官网浏览并核对所选素材说明。'},
 {'id': '3dtextures',
  'name': '3DTextures.me',
  'kinds': ['texture'],
  'mode': 'external',
  'defaultKind': 'texture',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://3dtextures.me/',
  'note': '无缝 PBR 材质与纹理；打开网站分类浏览。'},
 {'id': 'gameicons',
  'name': 'Game-icons.net',
  'kinds': ['other'],
  'mode': 'external',
  'defaultKind': 'other',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://game-icons.net/',
  'note': '游戏 SVG／PNG 图标；官网列明 CC BY 3.0，使用时保留作者署名。'},
 {'id': 'craftpix',
  'name': 'CraftPix',
  'kinds': ['vfx', 'other'],
  'mode': 'external',
  'defaultKind': 'other',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://craftpix.net/',
  'note': '2D 精灵、UI、图标与特效素材包；免费与付费混合，按包核对条款。'},
 {'id': 'freesound',
  'name': 'Freesound',
  'kinds': ['other'],
  'mode': 'external',
  'defaultKind': 'other',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://freesound.org/',
  'note': '社区音效与环境声；许可逐条不同，下载可能需要账户。'},
 {'id': 'sonniss',
  'name': 'Sonniss · GameAudioGDC',
  'kinds': ['other'],
  'mode': 'external',
  'defaultKind': 'other',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://sonniss.com/gameaudiogdc/',
  'note': '游戏音效合集与归档；可能是大型压缩包，先查看内容与许可。'},
 {'id': 'aigei',
  'name': '爱给网',
  'kinds': ['model', 'texture', 'vfx', 'other'],
  'mode': 'external',
  'defaultKind': 'other',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://www.aigei.com/index',
  'note': '中文音效、配乐、模型与游戏素材目录；免费、账户与商用条件按项核对。'},
 {'id': 'cgmodel',
  'name': 'CG模型网',
  'kinds': ['model', 'texture', 'other'],
  'mode': 'external',
  'defaultKind': 'model',
  'core': False,
  'group': 'catalog',
  'browseUrl': 'https://www.cgmodel.com/',
  'note': '中文 3D 模型与制作素材社区；按项查看文件格式、价格和使用条件。'},
 {'id': 'bing',
  'name': 'Bing · 联网发现',
  'kinds': ['model', 'texture', 'hdri', 'vfx', 'other'],
  'mode': 'external',
  'defaultKind': 'other',
  'core': False,
  'group': 'web',
  'searchUrlTemplate': 'https://www.bing.com/search?q={query}%20game%20assets',
  'note': '结合 game assets 继续发现素材网站；在浏览器查看结果。'},
 {'id': 'google',
  'name': 'Google · 联网发现',
  'kinds': ['model', 'texture', 'hdri', 'vfx', 'other'],
  'mode': 'external',
  'defaultKind': 'other',
  'core': False,
  'group': 'web',
  'searchUrlTemplate': 'https://www.google.com/search?q={query}%20game%20assets',
  'note': '结合 game assets 继续发现素材网站；在浏览器查看结果。'},
 {'id': 'baidu',
  'name': '百度 · 联网发现',
  'kinds': ['model', 'texture', 'hdri', 'vfx', 'other'],
  'mode': 'external',
  'defaultKind': 'other',
  'core': False,
  'group': 'web',
  'browseUrl': 'https://www.baidu.com/',
  'note': '中文网页发现；打开百度后在网站搜索，未接入结果预览。'}]
