(() => {
  "use strict";
  const node = (tag, text = "", className = "") => { const el = document.createElement(tag); el.textContent = text; el.className = className; return el; };
  const uuid = () => globalThis.crypto?.randomUUID?.() || "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, c => { const n = Math.floor(Math.random() * 16); return (c === "x" ? n : (n & 3) | 8).toString(16); });
  const label = (text, input) => { const el = node("label", "", "workflow-field"); el.append(node("span", text), input); return el; };
  const button = (text, action, className = "") => { const el = node("button", text, `workflow-button ${className}`.trim()); el.type = "button"; el.addEventListener("click", action); return el; };
  const input = (type = "text") => { const el = node("input"); el.type = type; return el; };
  function select(items) { const el = node("select"); setOptions(el, items); return el; }
  function setOptions(el, items, value = el.value) { el.replaceChildren(); for (const item of items) { const option = node("option", item.name || item.label || item.id); option.value = item.id; el.append(option); } el.value = items.some(item => item.id === value) ? value : items[0]?.id || ""; }
  function blobStore() {
    if (window.PhoneStore) return { get: id => window.PhoneStore.get("settings", id), put: value => window.PhoneStore.put("settings", value), remove: id => window.PhoneStore.remove("settings", id) };
    let opened;
    const database = () => opened ||= new Promise((resolve, reject) => {
      if (!globalThis.indexedDB) { reject(new Error("浏览器无法保存待上传图片，请保持此页打开。")); return; }
      const request = indexedDB.open("codex-workflow-drafts-v1", 1);
      request.onupgradeneeded = () => request.result.createObjectStore("drafts", { keyPath: "id" });
      request.onsuccess = () => resolve(request.result); request.onerror = () => { opened = null; reject(request.error); };
    });
    const operation = async (mode, action) => { const db = await database(); return new Promise((resolve, reject) => { const tx = db.transaction("drafts", mode); let value; const request = action(tx.objectStore("drafts")); request.onsuccess = () => { value = request.result; }; tx.oncomplete = () => resolve(value); tx.onerror = tx.onabort = () => reject(tx.error || new Error("草稿保存失败。")); }); };
    return { get: id => operation("readonly", store => store.get(id)), put: value => operation("readwrite", store => store.put(value)), remove: id => operation("readwrite", store => store.delete(id)) };
  }
  function create(root, options = {}) {
    if (!root) return null;
    const phone = Boolean(options.phone), base = options.endpoint || (phone ? "/api/phone/workflow" : "/api/workflow"), key = `codexWorkflow.v1:${base}`, assets = options.assetStore || blobStore();
    let saved;
    try { saved = JSON.parse(localStorage.getItem(key) || "{}"); } catch { saved = {}; }
    const state = { active: false, private: false, generation: 0, sequence: 0, recordId: saved.recordId || "", newDraft: saved.newDraft === true, records: [], detail: null, config: null, busy: false, polling: false, loadingAssets: false, timer: 0, layout: saved.layout || "image-first", drafts: saved.drafts || {}, pendingCounts: saved.pendingCounts || {}, outbox: saved.outbox || [], appliedTranscripts: saved.appliedTranscripts || [], voiceJobIds: saved.voiceJobIds || [], pending: [], previews: [], selectedText: "", selectedMessageId: "", selectedAttachments: [], review: null, recorder: null, recognition: null, stream: null, recording: false, voiceStarting: false, primaryId: "" };
    const controllers = new Set(), status = node("p", "", "workflow-notice"); status.setAttribute("role", "status"); status.setAttribute("aria-live", "polite");
    const header = node("div", "", "workflow-header"), title = node("h2", "工作记录"), list = node("div", "", "workflow-records"), history = { generation: 0, loading: false, hasMore: false, cursor: "" }, moreRecords = button("更多历史", () => void loadMoreRecords());
    const refresh = button("刷新", () => void reload()), fresh = button("新记录", () => void newRecord()); header.append(title, fresh, refresh);
    if (!phone) header.append(button("模型与项目设置", () => { if (state.private || !state.active) return; settings.open = true; settings.scrollIntoView?.({ block: "start", behavior: "smooth" }); }));
    const workspace = node("div", "", "workflow-workspace"), imageArea = node("section", "", "workflow-images"), textArea = node("section", "", "workflow-text");
    const image = node("img"); image.alt = "当前工作图片"; const enlarge = button("查看大图", () => openImage(), "workflow-enlarge"), figure = node("div", "", "workflow-main-image"); figure.append(image, enlarge);
    const thumbnails = node("div", "", "workflow-thumbnails"), imageEmpty = node("p", "上传截图或选择已有图片，边看图边说。", "workflow-empty"); imageArea.append(figure, imageEmpty, thumbnails);
    const layout = select([{ id: "image-first", name: "图片优先" }, { id: "split", name: "图片与文字" }, { id: "image-only", name: "只看图片" }, { id: "text", name: "只看文字" }]); layout.value = state.layout;
    const viewTools = node("div", "", "workflow-view-tools"), importInput = input("file"); importInput.accept = "image/*"; importInput.multiple = true; importInput.hidden = true;
    const importButton = button("添加图片", () => importInput.click()), saveImages = button("保存图片到记录", () => void savePictures()), capture = button("截取电脑画面", () => prepareDispatch("截取电脑当前画面，并保存到这条工作记录。", { action: "capture_screen", projectId: state.detail?.record.projectId || state.config?.projects?.[0]?.id })), preview = button("运行指定预览", () => prepareDispatch("运行所选的已授权预览命令，将结果保存到这条工作记录。", { action: "command", projectId: state.detail?.record.projectId || state.config?.projects?.[0]?.id }));
    const computerActions = node("details", "", "workflow-computer-actions"), actionMenu = node("div"); computerActions.append(node("summary", "电脑动作"), actionMenu); actionMenu.append(capture, preview); viewTools.append(label("查看", layout), importButton); if (phone) viewTools.append(computerActions); else viewTools.append(capture, preview); viewTools.append(importInput);
    const explanation = node("details", "", "workflow-collapse"), explanationText = node("p"); explanation.append(node("summary", "记录说明"), explanationText);
    const conversation = node("details", "", "workflow-collapse workflow-conversation"), messages = node("div", "", "workflow-messages"); conversation.open = !phone; conversation.append(node("summary", "评价与讨论"), messages);
    const jobs = node("div", "", "workflow-jobs"), logs = node("details", "", "workflow-collapse"), logText = node("pre"); logs.append(node("summary", "执行日志"), logText); textArea.append(explanation, conversation, jobs, logs); workspace.append(imageArea, textArea);
    const composer = node("div", "", "workflow-composer"), draft = node("textarea"), composeActions = node("div", "", "workflow-compose-actions"); draft.rows = 3; draft.placeholder = "边看图片边输入或听写；发送前可修改。"; draft.setAttribute("aria-label", "评价、讨论或派工内容");
    const mic = button("麦克风", () => void microphone()), discuss = button("讨论", () => void sendDiscussion(), "workflow-primary"), execute = button("交给电脑", () => prepareDispatch(draft.value));
    composeActions.append(mic, discuss, execute); const pendingFiles = node("div", "", "workflow-pending"), selected = node("div", "", "workflow-selection"), selectedLabel = node("p"), sendSelection = button("所选文字交给电脑", () => prepareDispatch(state.selectedText, { selectedText: state.selectedText, sourceMessageId: state.selectedMessageId }));
    const composeInput = node("div", "", "workflow-compose-input"), quickAudio = phone ? button("录音文件", () => audioInput.click()) : null; composeInput.append(draft); if (quickAudio) composeInput.append(quickAudio);
    selected.append(selectedLabel, sendSelection, button("取消选择", () => { state.selectedText = ""; update(); })); composer.append(selected, pendingFiles, composeInput, composeActions);
    const review = node("section", "", "workflow-review"), reviewText = node("textarea"), resultPaths = node("textarea"), computer = input(), project = select([]), action = select([]), command = select([]); computer.readOnly = true; reviewText.rows = 5; resultPaths.rows = 3; resultPaths.placeholder = "renders/preview.png\nrenders/detail.jpg";
    review.append(node("h3", "确认交给电脑的内容"), label("可修改内容", reviewText), label("执行电脑", computer), label("项目", project), label("操作", action), label("已授权命令", command), label("项目内图片路径（每行一条，最多 4 张）", resultPaths));
    const reviewContext = node("p", "", "workflow-muted"), confirm = button("确认交给电脑", () => void dispatch(), "workflow-primary"); review.append(reviewContext, confirm, button("取消", () => { state.review = null; saveDraft(); update(); }));
    const outbox = node("div", "", "workflow-outbox"), settings = node("details", "", "workflow-collapse workflow-settings"); settings.append(node("summary", phone ? "电脑与模型" : "模型与项目设置"));
    const audioInput = input("file"), importAudio = button("导入录音并转写", () => audioInput.click()); audioInput.accept = ".wav,.mp3,.m4a,.mp4,.webm,.ogg,audio/wav,audio/mpeg,audio/mp4,audio/webm,audio/ogg"; audioInput.hidden = true; audioInput.setAttribute("aria-label", "选择已有录音");
    const modelStatus = node("p"), settingsFields = node("div", "", "workflow-setting-fields"), providerId = input(), endpoint = input("url"), model = input(), transcriptionModel = input(), keyEnv = input(), apiKey = input("password"), anonymous = input("checkbox"), protocol = select([{ id: "responses", name: "Responses" }, { id: "chat_completions", name: "Chat Completions" }]); apiKey.autocomplete = "new-password";
    const permissions = node("div", "", "workflow-permissions"), projectName = input(), projectId = input(), projectPath = input(), allowScripts = input("checkbox"), background = input("checkbox"), commandConfig = node("textarea"); commandConfig.rows = 5; commandConfig.placeholder = '{"commands":[{"id":"preview","name":"指定预览","argv":["C:/完整路径/python.exe","C:/项目/preview.py"]}],"scriptRunners":{"python":["C:/完整路径/python.exe"]}}';
    const schemaHelp = node("details", "", "workflow-collapse"); schemaHelp.append(node("summary", "命令与结果清单格式"), node("p", 'JSON 支持 commands（id、name、argv、timeout）与 scriptRunners（python、powershell 的 argv）。运行程序必须填完整路径。命令可用 {jobDir}、{outputDir}、{resultManifest}、{instruction}，也可读取对应 CONSOLE_WORKFLOW_* 环境变量。将图片写入 outputDir，并在 resultManifest 写入 UTF-8 JSON，例如 {"text":"预览完成","files":["preview.png"]}。files 是输出目录内的相对文件名，最多 4 个。'));
    settings.append(modelStatus, importAudio, audioInput, node("p", "一次选择一段 WAV、MP3、M4A、MP4、WebM 或 OGG 录音，文件不超过上传限制。转写后先审核文字，再讨论或派工。", "workflow-muted"));
    if (!phone) { settingsFields.append(label("电脑后台接收任务", background), button("保存后台接收设置", () => void configureBackground()), label("提供方 ID", providerId), label("API 地址", endpoint), label("协议", protocol), label("模型", model), label("语音转写模型", transcriptionModel), label("API key 环境变量（可选）", keyEnv), label("API key（只写入，不回显）", apiKey), label("本机服务不需要 API key（仅 loopback）", anonymous), button("保存模型设置", () => void configureModel()), permissions, label("项目 ID（已有 ID 会更新该项目）", projectId), label("项目名称", projectName), label("项目目录", projectPath), label("指定命令与脚本运行程序（JSON；留空保留已有配置）", commandConfig), schemaHelp, label("允许此项目运行模型脚本（Windows 账户权限）", allowScripts), button("保存项目授权", () => void configureProject())); settings.append(settingsFields); }
    const lightbox = node("div", "", "workflow-lightbox"), fullImage = node("img"); fullImage.alt = "工作图片大图"; lightbox.setAttribute("role", "dialog"); lightbox.setAttribute("aria-label", "查看工作图片大图"); lightbox.append(button("关闭大图", () => { lightbox.hidden = true; }), fullImage); lightbox.hidden = true;
    root.classList.add("workflow-panel"); root.dataset.phone = String(phone); root.replaceChildren(header, list, viewTools, saveImages, status, workspace, composer, review, outbox, settings, lightbox);
    function updateViewport() { if (!phone) return; const height = window.visualViewport?.height || window.innerHeight; if (Number.isFinite(height) && height > 0) root.style.setProperty("--workflow-visible-height", `${Math.round(height)}px`); }
    if (phone) { window.visualViewport?.addEventListener("resize", updateViewport); updateViewport(); }
    function notice(text, error = false) { status.textContent = text; status.dataset.error = String(error); options.onStatus?.(text, error); }
    const draftKey = () => state.recordId || "new", assetKey = (id = state.recordId) => `workflow:${base}:${id || "new"}`;
    function save() { try { localStorage.setItem(key, JSON.stringify({ recordId: state.recordId, newDraft: state.newDraft, layout: state.layout, drafts: state.drafts, pendingCounts: state.pendingCounts, outbox: state.outbox, appliedTranscripts: state.appliedTranscripts, voiceJobIds: state.voiceJobIds })); } catch { notice("文字草稿暂时无法保存，请保持此页打开。", true); } }
    function saveDraft() { if (state.review) state.review = { ...state.review, text: reviewText.value, paths: resultPaths.value, projectId: project.value, action: action.value, commandId: command.value }; state.drafts[draftKey()] = { text: draft.value, review: state.review ? { ...state.review } : null }; save(); }
    async function persistFiles() { state.pendingCounts[draftKey()] = state.pending.length; save(); try { await assets.put({ id: assetKey(), files: state.pending.map(item => ({ id: item.id, file: item.file })) }); return true; } catch (error) { notice(error.message || "附件草稿保存失败，请保持此页打开。", true); return false; } }
    function restoreDraft() { const value = state.drafts[draftKey()] || {}; draft.value = value.text || ""; state.review = value.review || null; if (state.review) { reviewText.value = state.review.text; fillReview(); } }
    async function restoreFiles() { const ticket = ++state.sequence, id = state.recordId; state.loadingAssets = true; releasePreviews(); state.pending = []; update(); try { const stored = await assets.get(assetKey(id)); if (ticket !== state.sequence || state.private) return; state.pending = (stored?.files || []).map(item => ({ ...item, preview: /^image\//.test(item.file.type) ? URL.createObjectURL(item.file) : "" })); state.pendingCounts[id || "new"] = state.pending.length; save(); state.previews = state.pending.map(item => item.preview).filter(Boolean); } catch (error) { notice(error.message || "无法读取图片草稿。", true); } finally { if (ticket === state.sequence) { state.loadingAssets = false; renderPending(); update(); } } }
    function releasePreviews() { state.previews.forEach(url => URL.revokeObjectURL(url)); state.previews = []; }
    async function call(path, body) {
      const ticket = state.generation, abort = new AbortController(); controllers.add(abort); const timer = window.setTimeout(() => abort.abort(), body instanceof FormData ? 90000 : 30000), json = body && !(body instanceof FormData);
      try { const response = await fetch(`${base}/${path}`, { method: body ? "POST" : "GET", credentials: "same-origin", mode: "same-origin", cache: "no-store", redirect: "error", signal: abort.signal, headers: { Accept: "application/json", ...(phone ? { "X-Codex-Phone": "1" } : {}), ...(json ? { "Content-Type": "application/json" } : {}) }, ...(body ? { body: json ? JSON.stringify(body) : body } : {}) });
        if (ticket !== state.generation) throw Object.assign(new Error("旧连接已取消。"), { cancelled: true }); const result = await response.json(); if (ticket !== state.generation) throw Object.assign(new Error("旧连接已取消。"), { cancelled: true });
        options.onConnectionState?.(response.status !== 401);
        if (!response.ok) { if (response.status === 401) { clear(); options.onAuth?.(); } throw new Error(result.error || `请求失败（${response.status}）。`); } return result;
      } catch (error) { if (ticket !== state.generation) throw Object.assign(error, { cancelled: true }); if (error instanceof TypeError || error.name === "AbortError") options.onConnectionState?.(false); throw error; } finally { controllers.delete(abort); window.clearTimeout(timer); }
    }
    function safeAsset(value) { try { const url = new URL(value, window.location.href); return url.origin === new URL(window.location.href).origin && url.pathname === `${base}/attachment` ? url.href : ""; } catch { return ""; } }
    function detailValue(result) { return result?.record ? { ...result, messages: result.messages || [], attachments: result.attachments || [], jobs: result.jobs || [] } : null; }
    function applyDetail(result) {
      const value = detailValue(result); if (!value || value.record.id !== state.recordId) return; state.detail = value;
      const preferred = value.record.primaryAttachmentId; if (preferred && preferred !== state.lastServerPrimary) { state.primaryId = preferred; state.lastServerPrimary = preferred; state.selectedAttachments = []; }
      if (!state.primaryId) state.primaryId = value.attachments.find(item => /^image\//.test(item.mimeType || item.mime || item.type || ""))?.id || "";
      for (const job of value.jobs) if (job.status === "succeeded" && job.result?.text && (state.voiceJobIds.includes(job.id) || [job.kind, job.action, job.type].some(kind => kind === "transcribe")) && !state.appliedTranscripts.includes(job.id)) { draft.value = `${draft.value}${draft.value ? "\n" : ""}${job.result.text}`; state.appliedTranscripts.push(job.id); saveDraft(); notice("语音已转成文字，请检查修改后再讨论或派工。"); }
      renderDetail(); update();
    }
    function schedule() { window.clearTimeout(state.timer); state.timer = state.active && !document.hidden ? window.setTimeout(() => void poll(), 2500) : 0; }
    async function poll() { if (!state.active || document.hidden || state.polling || state.busy || !state.recordId) { schedule(); return; } state.polling = true; const id = state.recordId; try { const result = await call(`record?id=${encodeURIComponent(id)}`); if (id === state.recordId) { applyDetail(result); if (state.lastPollError) { state.lastPollError = false; notice("连接已恢复，请检查任务实际状态；需要继续或重试的任务请明确操作。"); } } } catch (error) { if (!error.cancelled) { state.lastPollError = true; notice(error instanceof TypeError || error.name === "AbortError" ? "暂时连接不到电脑。已保存记录与已接受任务会保留，恢复连接后请检查实际状态；未送达内容可原请求重试。" : `电脑暂时无法提供任务状态：${error.message || "服务错误"}。已保存记录与已接受任务会保留，重新连接后请检查状态或重试。`, true); } } finally { state.polling = false; schedule(); } }
    function invalidateHistory() { history.generation += 1; history.loading = false; }
    async function reload() { if (state.voiceFinishing) await state.voiceFinishing.finished; if (!state.active || state.busy || document.hidden) return; const ticket = ++history.generation; history.loading = true; update(); try { const config = await call("config"); if (ticket !== history.generation) return; state.config = config; renderConfig(); const result = await call("records"); if (ticket !== history.generation) return; state.records = result.records || []; history.hasMore = Boolean(result.hasMore); history.cursor = state.records.at(-1)?.id || ""; if (!state.recordId && !state.newDraft && !state.drafts.new?.text && !state.pendingCounts.new && state.records[0]) state.recordId = state.records[0].id; renderRecords(); restoreDraft(); await restoreFiles(); if (ticket !== history.generation) return; if (state.recordId) await poll(); else renderDetail(); } catch (error) { if (ticket === history.generation && !error.cancelled) notice(error.message || "无法连接电脑，请重试。", true); } finally { if (ticket === history.generation) { history.loading = false; update(); } } }
    function renderRecords() { list.replaceChildren(); for (const record of state.records) { const row = button(record.title || "工作记录", () => void chooseRecord(record.id), "workflow-record"); row.setAttribute("aria-pressed", String(record.id === state.recordId)); list.append(row); } moreRecords.hidden = !history.hasMore; if (history.hasMore) list.append(moreRecords); }
    async function loadMoreRecords() { if (!state.active || state.private || state.busy || history.loading || !history.hasMore || !history.cursor) return; const ticket = history.generation, before = history.cursor; history.loading = true; update(); try { const result = await call(`records?before=${encodeURIComponent(before)}`); if (ticket !== history.generation) return; const records = result.records || [], known = new Set(state.records.map(item => item.id)); for (const record of records) if (!known.has(record.id)) { known.add(record.id); state.records.push(record); } history.cursor = records.at(-1)?.id || before; history.hasMore = Boolean(result.hasMore && records.length && history.cursor !== before); renderRecords(); notice("已加载更多历史记录。"); } catch (error) { if (ticket === history.generation && !error.cancelled) notice(`历史记录未能加载：${error.message || "连接中断"}。已显示的记录仍保留，请重试。`, true); } finally { if (ticket === history.generation) { history.loading = false; update(); } } }
    async function chooseRecord(id) { if (state.busy || state.recording || state.voiceStarting || state.voiceFinishing) return; invalidateHistory(); saveDraft(); state.recordId = id; state.newDraft = false; state.detail = null; state.primaryId = state.lastServerPrimary = ""; state.selectedText = state.selectedMessageId = ""; state.selectedAttachments = []; state.review = null; restoreDraft(); save(); renderRecords(); renderDetail(); await restoreFiles(); await poll(); }
    async function operation(path, payload) { const pending = state.outbox.find(item => { const { requestId, ...old } = item.payload; return item.path === path && JSON.stringify(old) === JSON.stringify(payload); }); if (pending) return deliver(pending); const item = { id: payload.requestId || uuid(), path, payload: { ...payload }, createdAt: Date.now() }; item.payload.requestId = item.id; state.outbox.push(item); save(); renderOutbox(); return deliver(item); }
    async function deliver(item) { try { const result = await call(item.path, item.payload); state.outbox = state.outbox.filter(entry => entry.id !== item.id); save(); renderOutbox(); return result; } catch (error) { if (!error.cancelled) { item.error = error.message || "连接中断"; save(); renderOutbox(); notice("未确认送达。草稿和请求编号已保留，重试不会重复派工。", true); } throw error; } }
    async function ensureRecord() { if (state.recordId) return state.recordId; const pending = state.outbox.find(item => item.path === "create" && !item.payload.recordId); const result = pending ? await deliver(pending) : await operation("create", { projectId: project.value || state.config?.projects?.[0]?.id || "", title: draft.value.trim().slice(0, 70) || "图片工作记录" });
      await acceptCreated(result); return state.recordId;
    }
    async function acceptCreated(result) { invalidateHistory(); const oldKey = assetKey(""); state.recordId = result.record.id; state.newDraft = false; state.drafts[state.recordId] = state.drafts.new || { text: draft.value }; delete state.drafts.new; state.pendingCounts[state.recordId] = state.pending.length; delete state.pendingCounts.new; state.records = [result.record, ...state.records.filter(record => record.id !== result.record.id)]; renderRecords(); save(); try { await assets.put({ id: assetKey(), files: state.pending.map(item => ({ id: item.id, file: item.file })) }); await assets.remove(oldKey); } catch { notice("记录已保存，图片草稿暂时无法保存，请保持此页打开。", true); } applyDetail(result); }
    async function newRecord() { if (state.busy || state.recording || state.voiceStarting || state.voiceFinishing) return; invalidateHistory(); saveDraft(); state.recordId = ""; state.newDraft = true; state.detail = null; state.primaryId = state.lastServerPrimary = ""; state.selectedText = state.selectedMessageId = ""; state.selectedAttachments = []; restoreDraft(); await restoreFiles(); renderDetail(); save(); }
    async function uploadPending(purpose = "images", voiceTicket = state.voiceEpoch || 0) { if (purpose === "transcribe") requireVoiceForeground(voiceTicket); const matches = item => purpose === "transcribe" ? /^audio\//.test(item.file.type) : /^image\//.test(item.file.type); const oldUpload = state.outbox.find(item => item.path === "upload" && item.payload.recordId === state.recordId && (item.payload.purpose || "images") === purpose); if (!state.pending.some(matches) && !oldUpload) return []; await ensureRecord(); if (purpose === "transcribe") requireVoiceForeground(voiceTicket); const existing = state.outbox.find(item => item.path === "upload" && item.payload.recordId === state.recordId && (item.payload.purpose || "images") === purpose), files = existing ? state.pending.filter(item => existing.payload.fileIds.includes(item.id)) : state.pending.filter(matches); if (existing && files.length !== existing.payload.fileIds.length) throw new Error("原请求的文件尚未读取，不能生成新请求。请恢复图片草稿后重试。"); const ids = files.map(item => item.id), entry = existing || { id: uuid(), path: "upload", payload: { recordId: state.recordId, fileIds: ids, purpose }, createdAt: Date.now() }; if (!existing) { state.outbox.push(entry); save(); }
      const data = new FormData(); data.append("requestId", entry.id); data.append("recordId", state.recordId); for (const item of files) data.append("files", item.file, item.file.name || "image.png");
      try { const result = await call("upload", data); const attached = (result.attachments || []).filter(item => !result.uploadedAttachmentIds || result.uploadedAttachmentIds.includes(item.id)); state.outbox = state.outbox.filter(item => item.id !== entry.id); state.pending = state.pending.filter(item => !ids.includes(item.id)); releasePreviews(); state.pending.forEach(item => { item.preview = /^image\//.test(item.file.type) ? URL.createObjectURL(item.file) : ""; }); state.previews = state.pending.map(item => item.preview).filter(Boolean); await persistFiles(); renderPending(); save(); renderOutbox(); if (result.messages || result.jobs) applyDetail(result); else if (state.detail) { state.detail.attachments.push(...attached.filter(item => !state.detail.attachments.some(old => old.id === item.id))); renderDetail(); } if (purpose === "transcribe") requireVoiceForeground(voiceTicket); const remaining = state.pending.some(matches) ? await uploadPending(purpose, voiceTicket) : []; const all = [...attached, ...remaining]; state.selectedAttachments = all.filter(item => /^image\//.test(item.mimeType || item.mime || item.type || "")).map(item => item.id); return all; } catch (error) { if (!error.cancelled && state.outbox.some(item => item.id === entry.id)) { entry.error = error.message; save(); renderOutbox(); notice("图片尚未确认上传，原文件和请求编号已保存。", true); } throw error; }
    }
    async function savePictures() { if (state.busy || state.recording || !state.pending.some(item => /^image\//.test(item.file.type))) return; state.busy = true; update(); try { await uploadPending(); notice("图片已保存到记录，可直接在手机查看。未开始讨论或执行任务。"); } catch (error) { if (!error.cancelled) notice(error.message || "图片未确认送达，请重试。", true); } finally { state.busy = false; update(); schedule(); } }
    function context(extra = {}) { const value = { attachmentIds: state.selectedAttachments.length ? [...state.selectedAttachments] : state.primaryId ? [state.primaryId] : [] }; for (const name of ["sourceMessageId", "selectedText", "optionId", "attachmentIds", "referenceIds"]) if (extra[name] !== undefined && extra[name] !== "") value[name] = extra[name]; value.attachmentIds = [...new Set(value.attachmentIds)].slice(-(state.config?.limits?.maxFiles || 4)); return value; }
    async function sendDiscussion() { if (state.busy || state.recording || state.voiceStarting || (!draft.value.trim() && !state.pending.length)) return; state.busy = true; update(); const text = draft.value.trim() ? draft.value : "请评价当前图片，并提出可讨论的改进方案。"; try { await ensureRecord(); await uploadPending(); const result = await operation("discuss", { recordId: state.recordId, projectId: project.value || state.detail?.record.projectId, text, context: context() }); draft.value = ""; saveDraft(); notice("已交给电脑讨论。讨论不会执行项目操作。"); await readAccepted(result); } catch (error) { if (!error.cancelled) notice(error.message || "未送达，请重试。", true); } finally { state.busy = false; update(); schedule(); } }
    async function readAccepted(result) { if (result.job) { if (!state.detail) state.detail = { record: result.record, messages: [], attachments: [], jobs: [] }; state.detail.jobs = [result.job, ...state.detail.jobs.filter(job => job.id !== result.job.id)]; renderDetail(); } else applyDetail(result); if (state.recordId && state.active) { const detail = await call(`record?id=${encodeURIComponent(state.recordId)}`); applyDetail(detail); } }
    function prepareDispatch(text, extra = {}) { if (state.busy || state.private || !text.trim()) return; state.review = { text, context: context(extra), projectId: extra.projectId || state.detail?.record.projectId || project.value, action: extra.action || "", commandId: extra.commandId || "", paths: "" }; reviewText.value = text; fillReview(); saveDraft(); update(); review.scrollIntoView?.({ block: "nearest", behavior: "smooth" }); }
    function fillReview() { if (!state.review) return; if (state.review.projectId) project.value = state.review.projectId; renderCommands(); action.value = state.review.action || ""; command.value = state.review.commandId || ""; resultPaths.value = state.review.paths || ""; }
    function reviewedPaths() { const paths = resultPaths.value.split(/\r?\n/).map(value => value.trim()).filter(Boolean); return paths.length >= 1 && paths.length <= 4 && paths.every(value => !/^(?:[a-z]:|[/\\])/i.test(value) && !value.includes("\0") && !value.split(/[/\\]/).includes("..") && /\.(?:png|jpe?g|gif|webp|heic|heif)$/i.test(value)) ? paths : null; }
    async function dispatch() { const paths = action.value === "result_import" ? reviewedPaths() : null; if (state.busy || !state.review || !reviewText.value.trim() || !project.value || !action.value || (action.value === "command" && !command.value) || action.value === "result_import" && !paths) return; state.busy = true; update(); const text = reviewText.value, extra = state.review.context; try { await ensureRecord(); const uploaded = await uploadPending(), attachmentIds = [...new Set([...(extra.attachmentIds || []), ...uploaded.filter(item => /^image\//.test(item.mimeType || item.mime || item.type || "")).map(item => item.id)])]; const result = await operation("submit", { recordId: state.recordId, text, computerId: state.config?.computer?.id, projectId: project.value, action: action.value, ...(action.value === "command" && command.value ? { commandId: command.value } : {}), ...(paths ? { args: { paths } } : {}), context: context({ ...extra, attachmentIds: attachmentIds.length ? attachmentIds : context().attachmentIds }) }); state.review = null; if (text === draft.value) draft.value = ""; saveDraft(); notice("电脑已接受任务。离开手机页面后任务仍会继续。"); await readAccepted(result); } catch (error) { if (!error.cancelled) notice(error.message || "派工未确认送达，请重试。", true); } finally { state.busy = false; update(); schedule(); } }
    function renderPending() { pendingFiles.replaceChildren(); for (const item of state.pending) { const row = node("div", "", "workflow-pending-file"); if (item.preview) { const thumb = node("img"); thumb.src = item.preview; thumb.alt = item.file.name; row.append(thumb); } row.append(node("span", item.file.name || "图片")); if (/^audio\//.test(item.file.type)) row.append(button("上传录音并转写", () => void transcribePending())); row.append(button("移除", () => { if (state.busy) return; if (item.preview) URL.revokeObjectURL(item.preview); state.pending = state.pending.filter(old => old.id !== item.id); void persistFiles(); renderPending(); update(); })); pendingFiles.append(row); } }
    async function queueFiles(files) { if (state.recording || state.voiceStarting || state.voiceFinishing || state.private || !state.active || document.hidden) return; if (state.pending.length + files.length > (state.config?.limits?.maxFiles || 4)) { notice("一次最多保留 4 个待上传文件，请先发送或移除。", true); return; } for (const file of files) { const max = state.config?.limits?.maxFileBytes || 12 * 1024 ** 2; if (!file.size || file.size > max || !/^image\//.test(file.type)) { notice("请选择有效图片，单张不超过上传限制。", true); return; } } for (const file of files) { const preview = URL.createObjectURL(file); state.pending.push({ id: uuid(), file, preview }); state.previews.push(preview); } await persistFiles(); renderPending(); update(); }
    function renderDetail() { image.hidden = !state.detail; thumbnails.replaceChildren(); messages.replaceChildren(); jobs.replaceChildren(); logText.textContent = ""; explanationText.textContent = state.detail?.record.description || state.detail?.record.title || ""; title.textContent = phone ? "工作记录" : state.detail?.record.title || "工作记录";
      const attachments = state.detail?.attachments || [], main = attachments.find(item => item.id === state.primaryId), url = safeAsset(main?.previewUrl || main?.url); image.src = url; image.hidden = !url; enlarge.hidden = !url; imageEmpty.hidden = Boolean(url);
      for (const asset of attachments.filter(item => /^image\//.test(item.mimeType || item.mime || item.type || ""))) { const url = safeAsset(asset.previewUrl || asset.url); if (!url) continue; const thumb = node("img"); thumb.src = url; thumb.alt = asset.name || "工作图片"; const pick = button("", () => { state.primaryId = asset.id; state.selectedAttachments = [asset.id]; renderDetail(); update(); }, "workflow-thumbnail"); pick.setAttribute("aria-label", `查看并引用 ${asset.name || "图片"}`); pick.setAttribute("aria-pressed", String(asset.id === state.primaryId)); pick.append(thumb); thumbnails.append(pick); }
      for (const asset of attachments.filter(item => /^audio\//.test(item.mimeType || item.mime || item.type || ""))) messages.append(button(`转写录音：${asset.name || "录音"}`, () => void transcribeAttachment(asset.id)));
      for (const message of state.detail?.messages || []) { const card = node("article", "", "workflow-message"); card.dataset.messageId = message.id; card.append(node("strong", { user: "你", assistant: "电脑讨论", transcript: "语音文字", result: "执行结果" }[message.role] || message.role || "记录"), node("p", message.text || message.content || ""));
        if (["assistant", "result"].includes(message.role)) { card.append(button("整条交给电脑", () => prepareDispatch(message.text || message.content || "", { sourceMessageId: message.id }))); for (const option of message.options || []) card.append(button(`执行方案：${option.label || option.title || option.id}`, () => prepareDispatch(option.instruction || option.text || option.description || option.label || option.title || "", { sourceMessageId: message.id, optionId: option.id, projectId: option.projectId, action: option.action, commandId: option.commandId }), "workflow-option")); } messages.append(card); }
      const names = { queued: "等待电脑", running: "电脑执行中", succeeded: "完成", failed: "失败", waiting: "等待处理", interrupted: "中断" };
      for (const job of state.detail?.jobs || []) { const card = node("article", "", "workflow-job"); card.dataset.jobId = job.id; card.dataset.status = job.status; card.append(node("strong", names[job.status] || job.status), node("p", job.text || job.instruction || job.action || "")); if (job.progress) card.append(node("p", String(job.progress))); if (job.error) card.append(node("p", job.error, "workflow-error")); if (["failed", "interrupted", "waiting"].includes(job.status)) card.append(button(job.status === "waiting" ? "继续任务" : "重试任务", () => void retryJob(job.id))); jobs.append(card); logText.textContent += `${job.id} · ${names[job.status] || job.status}\n${Array.isArray(job.log) ? job.log.join("\n") : job.log || ""}\n`; }
    }
    function openImage() { const asset = state.detail?.attachments.find(item => item.id === state.primaryId), url = safeAsset(asset?.url); if (url) { fullImage.src = url; lightbox.hidden = false; } }
    async function retryJob(jobId) { if (state.busy) return; state.busy = true; update(); try { await readAccepted(await operation("retry", { jobId })); } catch (error) { if (!error.cancelled) notice(error.message, true); } finally { state.busy = false; update(); schedule(); } }
    function renderOutbox() { outbox.hidden = state.private; outbox.replaceChildren(); for (const item of state.outbox) { const row = node("div", "", "workflow-unsent"), retry = button("原请求重试", () => void retryOutbox(item)); retry.disabled = state.busy || state.private || !state.active; row.append(node("span", `未确认送达 · ${item.path === "submit" ? "电脑任务" : item.path === "upload" ? "图片" : item.path === "discuss" ? "讨论" : "记录"}`), retry); outbox.append(row); } }
    async function retryOutbox(item) { if (state.busy || state.private || !state.active || document.hidden) return; const voiceTicket = state.voiceEpoch || 0; state.busy = true; update(); try { if (item.path === "create" || item.payload.recordId && item.payload.recordId !== state.recordId) { saveDraft(); state.recordId = item.path === "create" ? "" : item.payload.recordId; state.newDraft = item.path === "create"; state.detail = null; restoreDraft(); await restoreFiles(); } if (item.path === "upload") { const uploaded = await uploadPending(item.payload.purpose, voiceTicket); if (item.payload.purpose === "transcribe") { const audio = uploaded.find(asset => /^audio\//.test(asset.mimeType || asset.mime || asset.type || "")); if (audio) await requestTranscript(audio.id, voiceTicket); } } else { const result = await deliver(item); if (item.path === "create") await acceptCreated(result); else { if (["discuss", "submit"].includes(item.path)) { if (draft.value === item.payload.text) draft.value = ""; if (item.path === "submit" && reviewText.value === item.payload.text) state.review = null; saveDraft(); } await readAccepted(result); } } notice("已确认送达。"); } catch (error) { if (!error.cancelled) notice(error.message || "尚未送达，请稍后重试。", true); } finally { state.busy = false; update(); schedule(); } }
    function renderConfig() { const config = state.config || {}, models = config.models || {}; modelStatus.textContent = models.ready ? `电脑：${config.computer?.name || "已连接"} · 模型已配置` : "电脑模型尚未配置，需要在电脑填写模型与服务认证。"; modelStatus.textContent += models.transcriptionReady ? " · 录音转写已配置" : " · 录音转写尚未配置，可使用系统键盘听写"; if (phone) { modelStatus.textContent += ` · 可用项目：${(config.projects || []).map(item => item.name).join("、") || "未授权"}`; }
      computer.value = config.computer?.name || ""; setOptions(project, [{ id: "", name: "选择项目" }, ...(config.projects || [])]); setOptions(action, [{ id: "", name: "选择电脑操作" }, ...(config.actions || [])]); renderCommands();
      if (!phone) { background.checked = config.backgroundEnabled === true; const current = (models.providers || []).find(item => item.id === models.selected) || {}; providerId.value = current.id || "default"; endpoint.value = current.endpoint || ""; model.value = current.model || ""; transcriptionModel.value = current.transcriptionModel || ""; keyEnv.value = current.keyEnv || ""; protocol.value = current.protocol || "responses"; anonymous.checked = current.allowAnonymous === true; permissions.replaceChildren(); for (const item of config.projects || []) permissions.append(node("p", `${item.name} · ${(item.capabilities || []).join("、") || "无执行授权"}${item.allowGeneratedScripts ? " · 允许模型脚本（Windows 账户权限）" : ""}`)); } fillReview(); }
    function renderCommands() { const current = state.config?.projects?.find(item => item.id === project.value); setOptions(command, [{ id: "", name: "选择已授权命令" }, ...(current?.commands || [])]); }
    async function configureModel() { if (phone || state.busy) return; if (anonymous.checked) { try { if (!["localhost", "127.0.0.1", "[::1]"].includes(new URL(endpoint.value.trim()).hostname)) throw new Error(); } catch { notice("无 API key 的服务仅允许本机 loopback 地址。", true); return; } } state.busy = true; update(); const payload = { id: providerId.value || "default", endpoint: endpoint.value.trim(), protocol: protocol.value, model: model.value.trim(), transcriptionModel: transcriptionModel.value.trim(), keyEnv: keyEnv.value.trim(), allowAnonymous: anonymous.checked === true, ...(apiKey.value ? { key: apiKey.value } : {}) }; try { await (options.configureModel ? options.configureModel(payload) : call("models", payload)); apiKey.value = ""; state.config = await call("config"); renderConfig(); notice("模型设置已保存。"); } catch (error) { if (!error.cancelled) notice(error.message || "模型保存失败。", true); } finally { state.busy = false; update(); } }
    async function configureProject() { if (phone || state.busy || !projectId.value.trim() || !projectPath.value.trim()) return; let advanced = {}; try { if (commandConfig.value.trim()) advanced = JSON.parse(commandConfig.value); if (!advanced || Array.isArray(advanced) || typeof advanced !== "object" || Object.keys(advanced).some(key => !["commands", "scriptRunners"].includes(key))) throw new Error(); } catch { notice("命令 JSON 只接受 commands 与 scriptRunners，请检查格式。", true); return; }
      const previous = state.config?.projects?.find(item => item.id === projectId.value.trim()); if (allowScripts.checked && !previous && !Object.keys(advanced.scriptRunners || {}).length) { notice("请先在 JSON 填写 Python 或 PowerShell 的完整运行程序路径。", true); return; }
      state.busy = true; update(); const capabilities = [...new Set([...(previous?.capabilities || ["capture_screen", "result_import"]).filter(item => item !== "generated_script"), ...(allowScripts.checked ? ["generated_script"] : []), ...(advanced.commands?.length ? ["command"] : [])])], projectValue = { id: projectId.value.trim(), name: projectName.value.trim() || projectId.value.trim(), root: projectPath.value.trim(), capabilities, allowGeneratedScripts: allowScripts.checked === true, ...advanced }; try { const payload = { project: projectValue }; await (options.configureProjects ? options.configureProjects(payload) : call("projects", payload)); state.config = await call("config"); renderConfig(); notice("项目授权已保存。"); } catch (error) { if (!error.cancelled) notice(error.message || "项目授权保存失败。", true); } finally { state.busy = false; update(); } }
    async function configureBackground() { if (phone || state.busy) return; state.busy = true; update(); try { await call("background", { enabled: background.checked === true }); state.config = await call("config"); renderConfig(); notice("后台接收设置已保存。"); } catch (error) { if (!error.cancelled) notice(error.message, true); } finally { state.busy = false; update(); } }
    function update() { root.dataset.layout = state.layout; const locked = state.busy || state.loadingAssets || state.voiceFinishing || state.private || !state.active; refresh.disabled = fresh.disabled = importButton.disabled = importAudio.disabled = capture.disabled = preview.disabled = locked || state.recording || state.voiceStarting; if (quickAudio) quickAudio.disabled = importAudio.disabled; refresh.disabled ||= history.loading; moreRecords.disabled = locked || history.loading; saveImages.hidden = state.private || !state.pending.some(item => /^image\//.test(item.file.type)); saveImages.disabled = locked || state.recording || saveImages.hidden; discuss.disabled = locked || state.recording || state.voiceStarting || !draft.value.trim() && !state.pending.some(item => /^image\//.test(item.file.type)); execute.disabled = locked || state.recording || state.voiceStarting || !draft.value.trim(); mic.disabled = locked || state.voiceStarting; mic.textContent = state.recording ? "停止听写／录音" : "麦克风"; review.hidden = !state.review || state.private; selected.hidden = !state.selectedText || state.private; selectedLabel.textContent = state.selectedText.slice(0, 300); sendSelection.disabled = locked; command.parentElement.hidden = action.value !== "command"; resultPaths.parentElement.hidden = action.value !== "result_import"; confirm.disabled = locked || !reviewText.value.trim() || !project.value || !action.value || action.value === "command" && !command.value || action.value === "result_import" && !reviewedPaths(); reviewContext.textContent = action.value === "result_import" ? "选择项目内已存在的图片路径；电脑会校验文件与授权范围。只有确认后才导入。" : `关联当前图片 ${state.review?.context?.attachmentIds?.length || state.selectedAttachments.length || (state.primaryId ? 1 : 0)} 张${state.review?.context?.sourceMessageId ? " · 来源：所选讨论" : ""}。只有确认后才执行。`; settings.hidden = state.private; workspace.hidden = composer.hidden = state.private; renderOutbox(); }
    const voiceForeground = ticket => ticket === (state.voiceEpoch || 0) && state.active && !state.private && !document.hidden;
    function requireVoiceForeground(ticket) { if (!voiceForeground(ticket)) throw Object.assign(new Error("录音已保留，回到此页后请手动上传转写。"), { cancelled: true }); }
    function currentVoice(session) { return state.voiceSession === session && session.generation === state.generation && !session.paused && voiceForeground(session.epoch); }
    function releaseVoice(session) { window.clearTimeout(session.timer); if (session.stream && !session.tracksStopped) { session.tracksStopped = true; session.stream.getTracks().forEach(track => track.stop()); } if (state.voiceSession === session) { state.voiceSession = state.recognition = state.recorder = state.stream = null; state.recording = state.voiceStarting = false; } }
    function stopVoice(reason = "manual") {
      const session = state.voiceSession; if (!session) return;
      window.clearTimeout(session.timer); session.paused = reason !== "manual"; session.upload = reason === "manual";
      if (session.recognition) { if (session.paused) { releaseVoice(session); try { (session.recognition.abort || session.recognition.stop)?.call(session.recognition); } catch {} notice("听写已停止，已收到的文字已保留。回到此页后可修改再发送。"); } else { try { session.recognition.stop(); } catch { releaseVoice(session); notice("听写已停止，已收到的文字已保留。", true); } } }
      else if (session.recorder) { if (reason !== "clear") state.voiceFinishing = session; releaseVoice(session); try { if (session.recorder.state !== "inactive") session.recorder.stop(); else void finishRecording(session); } catch { void finishRecording(session); } }
      else releaseVoice(session);
      update();
    }
    async function finishRecording(session) {
      if (session.finalized) return; session.finalized = true; releaseVoice(session);
      try {
        if (session.generation !== state.generation || state.private) return;
        const type = (session.recorder.mimeType || session.mime || "audio/webm").split(";")[0], file = new File(session.chunks, `voice-${uuid()}.${type.includes("mp4") ? "m4a" : type.includes("ogg") ? "ogg" : "webm"}`, { type });
        if (!file.size) { notice("没有收到录音内容，请重试或使用系统键盘听写。", true); return; }
        await transcribe(file, { upload: session.upload && voiceForeground(session.epoch), ticket: session.epoch });
      } finally { if (state.voiceFinishing === session) state.voiceFinishing = null; session.resolveFinished(); update(); schedule(); }
    }
    async function microphone() {
      if (state.recording) { stopVoice(); return; } if (state.busy || state.voiceStarting || state.voiceFinishing || state.private || !state.active || document.hidden) return;
      if (!window.isSecureContext) { draft.focus(); notice("本页不能录音，请使用键盘麦克风听写，无需 API；说话时图片仍在上方。"); return; }
      const session = { generation: state.generation, epoch: state.voiceEpoch || 0, recordId: state.recordId, chunks: [], upload: true, paused: false }; session.finished = new Promise(resolve => { session.resolveFinished = resolve; }); state.voiceSession = session;
      const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition;
      if (Recognition) {
        const recognition = new Recognition(), before = draft.value; let received = false, failed = false; session.recognition = state.recognition = recognition; recognition.lang = options.language || "zh-CN"; recognition.continuous = true; recognition.interimResults = true; state.recording = true;
        recognition.onresult = event => { if (!currentVoice(session) || failed) return; const text = Array.from(event.results).map(result => result[0]?.transcript || "").join(""); if (!text.trim()) return; received = true; draft.value = `${before}${before ? "\n" : ""}${text}`; saveDraft(); update(); };
        recognition.onend = () => { if (!currentVoice(session)) return; releaseVoice(session); update(); if (!failed) notice(received ? "听写结束，请修改后再发送。" : "没有收到听写文字，请重试或使用键盘麦克风。", !received); };
        recognition.onerror = () => { if (!currentVoice(session)) return; failed = true; releaseVoice(session); draft.focus(); update(); notice(received ? "听写已中断，收到的文字已保留，请检查后再发送。" : "没有收到听写文字，此页听写失败，请使用键盘麦克风。", true); };
        try { recognition.start(); session.timer = window.setTimeout(() => { if (currentVoice(session)) stopVoice(); }, 180000); update(); notice("正在听写，图片仍可查看。停止后可修改文字，最多三分钟。"); } catch { failed = true; releaseVoice(session); update(); draft.focus(); notice("无法开始听写，请使用键盘麦克风。", true); } return;
      }
      const Recorder = window.MediaRecorder || globalThis.MediaRecorder;
      if (!navigator.mediaDevices?.getUserMedia || !Recorder) { releaseVoice(session); draft.focus(); notice("本页不能录音，请使用键盘麦克风听写，无需 API；说话时图片仍在上方。"); return; }
      if (state.pending.length >= (state.config?.limits?.maxFiles || 4) || state.pending.some(item => /^audio\//.test(item.file.type))) { releaseVoice(session); notice("已有录音或待上传文件已达到限制，请先上传或移除，再开始录音。", true); return; }
      state.voiceStarting = true; update();
      try {
        const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); session.stream = stream; if (!currentVoice(session)) { releaseVoice(session); return; } state.stream = stream;
        session.mime = ["audio/webm;codecs=opus", "audio/mp4", "audio/webm", "audio/ogg"].find(type => Recorder.isTypeSupported?.(type)); const recorder = session.mime ? new Recorder(stream, { mimeType: session.mime }) : new Recorder(stream); session.recorder = state.recorder = recorder;
        recorder.ondataavailable = event => { if (!session.finalized && event.data?.size) session.chunks.push(event.data); };
        recorder.onstop = () => { if (state.voiceSession === session) state.voiceFinishing = session; void finishRecording(session); };
        recorder.onerror = () => { if (state.voiceSession !== session || session.generation !== state.generation || state.private) return; stopVoice("paused"); notice("录音已中断，已有内容保留为草稿；请检查后手动上传转写。", true); };
        recorder.start(1000); state.recording = true; session.timer = window.setTimeout(() => { if (currentVoice(session) && recorder.state !== "inactive") stopVoice(); }, 180000); notice("正在录音，图片仍可查看。再次点击停止并转写，最多录三分钟。");
      } catch { if (state.voiceSession === session) { releaseVoice(session); update(); draft.focus(); notice("无法使用麦克风，请使用系统键盘听写。", true); } }
      finally { if (state.voiceSession === session) { state.voiceStarting = false; update(); } }
    }
    async function requestTranscript(attachmentId, ticket = state.voiceEpoch || 0) { requireVoiceForeground(ticket); const result = await operation("transcribe", { recordId: state.recordId, attachmentId }); if (result.job) { state.voiceJobIds.push(result.job.id); save(); } notice(result.job?.status === "waiting" || state.config?.models?.transcriptionReady === false ? "录音已保存，等待电脑配置语音转写模型。配置后请点“继续任务”；不会自动讨论或执行。" : "录音已交给电脑转写，文字会回到编辑框；不会自动执行。"); await readAccepted(result); }
    async function transcribeAttachment(attachmentId) { if (state.busy || state.private || !state.active || document.hidden) return; state.busy = true; update(); try { await requestTranscript(attachmentId); } catch (error) { if (!error.cancelled) notice(error.message || "转写未送达，请重试。", true); } finally { state.busy = false; update(); schedule(); } }
    function checkedAudio(file) { const types = { wav: "audio/wav", mp3: "audio/mpeg", m4a: "audio/mp4", mp4: "audio/mp4", webm: "audio/webm", ogg: "audio/ogg" }, suffix = file?.name?.split(".").pop()?.toLowerCase(), canonical = types[suffix], type = (file?.type || "").toLowerCase().split(";")[0], max = state.config?.limits?.maxFileBytes || 12 * 1024 ** 2; if (!file?.size || file.size > max || !canonical || type && ![canonical, "application/octet-stream", "audio/x-wav", "audio/x-m4a", "video/webm", "video/mp4"].includes(type)) { notice("请选择有效 WAV、MP3、M4A、MP4、WebM 或 OGG 录音，单个文件不超过上传限制。", true); return null; } if (state.pending.length >= (state.config?.limits?.maxFiles || 4)) { notice("待上传文件已达到限制，请先发送或移除。", true); return null; } if (state.pending.some(item => /^audio\//.test(item.file.type))) { notice("已有录音尚未送达，请先上传转写或移除原录音。", true); return null; } return type === canonical && file.type === canonical ? file : new File([file], file.name, { type: canonical }); }
    async function transcribe(file, { upload = true, ticket = state.voiceEpoch || 0 } = {}) { if (state.private || state.busy) return; const audio = checkedAudio(file); if (!audio) return; const generation = state.generation; state.busy = true; state.pending.push({ id: uuid(), file: audio, preview: "" }); update(); const durable = await persistFiles(); if (generation !== state.generation || state.private) return; state.busy = false; renderPending(); update(); if (upload && voiceForeground(ticket)) await transcribePending(); else notice(durable ? "录音已保留为草稿，回到此页后请点“上传录音并转写”。" : "录音草稿未能持久保存，请保持此页打开，回到此页后手动上传转写。", !durable); schedule(); }
    async function transcribePending() { if (state.private || state.busy || !state.active || document.hidden || !state.pending.some(item => /^audio\//.test(item.file.type))) return; const ticket = state.voiceEpoch || 0; state.busy = true; update(); try { await ensureRecord(); requireVoiceForeground(ticket); const uploaded = await uploadPending("transcribe", ticket), asset = uploaded.find(item => /^audio\//.test(item.mimeType || item.mime || item.type || "")); if (!asset) throw new Error("录音未能保存，请重试。"); await requestTranscript(asset.id, ticket); } catch (error) { if (!error.cancelled) notice(`${error.message || "语音未送达"}。录音已保留，可原请求重试。`, true); else if (!state.private) notice("录音或已上传附件已保留，回到此页后请手动上传或选择附件转写。"); } finally { state.busy = false; update(); schedule(); } }
    audioInput.addEventListener("change", () => { const files = Array.from(audioInput.files || []); audioInput.value = ""; if (state.busy || state.recording || state.voiceStarting || state.voiceFinishing || state.private || !state.active || document.hidden) return; if (files.length !== 1) { if (files.length) notice("一次只导入一段录音，请重新选择。", true); return; } void transcribe(files[0]); });
    draft.addEventListener("input", () => { saveDraft(); update(); }); reviewText.addEventListener("input", () => { saveDraft(); update(); }); resultPaths.addEventListener("input", () => { saveDraft(); update(); }); project.addEventListener("change", () => { renderCommands(); saveDraft(); update(); }); action.addEventListener("change", () => { saveDraft(); update(); }); command.addEventListener("change", () => { saveDraft(); update(); }); layout.addEventListener("change", () => { state.layout = layout.value; save(); update(); }); importInput.addEventListener("change", () => { const files = Array.from(importInput.files || []); importInput.value = ""; if (!state.busy) void queueFiles(files); });
    composer.addEventListener("paste", event => { if (state.busy) return; const items = Array.from(event.clipboardData?.items || []).filter(item => item.kind === "file").map(item => item.getAsFile()).filter(Boolean), files = (items.length ? items : Array.from(event.clipboardData?.files || [])).filter(file => /^image\//.test(file.type)); if (files.length) { event.preventDefault(); void queueFiles(files.map((file, index) => file.name ? file : new File([file], `pasted-${index}.png`, { type: file.type }))); } });
    function selectionMessage(value) { let element = value?.nodeType === 3 ? value.parentElement : value; while (element && element !== messages) { if (["INPUT", "TEXTAREA", "BUTTON", "SELECT", "OPTION", "SUMMARY", "AUDIO", "VIDEO"].includes(element.tagName) || element.isContentEditable) return null; if (element.dataset?.messageId) return messages.contains(element) ? element : null; element = element.parentElement; } return null; }
    document.addEventListener("selectionchange", () => { if (state.private) return; const selection = window.getSelection?.(); if (!selection) return; const message = selectionMessage(selection.anchorNode); if (!message || message !== selectionMessage(selection.focusNode)) return; const text = String(selection).trim(); if (!text) return; state.selectedText = text.slice(0, 20000); state.selectedMessageId = message.dataset.messageId; update(); });
    document.addEventListener("visibilitychange", () => { window.clearTimeout(state.timer); state.timer = 0; if (document.hidden) { state.voiceEpoch = (state.voiceEpoch || 0) + 1; if (!state.private) saveDraft(); stopVoice("paused"); } else if (state.active) void poll(); });
    function clear() { if (state.private) return; invalidateHistory(); history.hasMore = false; saveDraft(); state.generation += 1; state.sequence += 1; state.voiceEpoch = (state.voiceEpoch || 0) + 1; state.active = false; state.private = true; controllers.forEach(controller => controller.abort()); controllers.clear(); window.clearTimeout(state.timer); stopVoice("clear"); state.voiceFinishing = null; state.busy = state.recording = state.voiceStarting = false; state.detail = null; state.records = []; state.selectedText = ""; state.review = null; state.pending = []; releasePreviews(); draft.value = reviewText.value = apiKey.value = ""; image.src = fullImage.src = ""; lightbox.hidden = true; list.replaceChildren(); renderDetail(); update(); }
    restoreDraft(); renderPending(); renderDetail(); update();
    return { setActive(value) { const changed = state.active !== Boolean(value); state.active = Boolean(value); if (state.active && changed) { state.private = false; restoreDraft(); if (state.voiceFinishing) void state.voiceFinishing.finished.then(() => { if (state.active && !state.private) void reload(); }); else void reload(); } else if (!state.active) { state.voiceEpoch = (state.voiceEpoch || 0) + 1; if (!state.private) saveDraft(); window.clearTimeout(state.timer); stopVoice("paused"); } update(); }, refresh: reload, clear, hasDraft() { return Boolean(apiKey.value || state.busy || state.recording || state.voiceStarting || state.voiceFinishing || state.pending.length || Object.values(state.pendingCounts).some(count => count > 0) || state.outbox.length || Object.values(state.drafts).some(item => item.text?.trim() || item.review)); }, selectRecord: chooseRecord };
  }
  window.CodexWorkflowPanel = { create };
})();
